# Generated by Selenium IDE
import sys
import pytest
import time
from subprocess import Popen
import json
import threading
import ctypes
import multiprocessing
import os
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support.ui import Select

sys.stdin.reconfigure(encoding='utf-8')
sys.stdout.reconfigure(encoding='utf-8')
class TestFinish():
  def setup_method(self):
    self.driver = webdriver.Chrome("C:\Program Files (x86)\chromedriver.exe")
    self.vars = {}
  
  def teardown_method(self):
    self.driver.close()
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_finish(self):
    self.driver.get("https://www.preinscriptions.uninet.cm/")
    self.driver.set_window_size(976, 1056)
    self.driver.find_element(By.LINK_TEXT, "Faculté des Sciences (FS)").click()
    self.driver.find_element(By.ID, "id_nom").click()
    self.driver.find_element(By.ID, "id_nom").send_keys(sys.argv[1].replace('_', ' '))
    self.driver.find_element(By.ID, "id_prenom").send_keys(sys.argv[2].replace('_', ' '))
    self.driver.find_element(By.ID, "id_datenaissance").click()
    self.driver.find_element(By.ID, "id_datenaissance").send_keys(sys.argv[3].replace('_', ' '))
    self.driver.find_element(By.ID, "id_dateprecise_1").click()
    self.driver.find_element(By.ID, "id_lieunaissance").click()
    self.driver.find_element(By.ID, "id_lieunaissance").send_keys(sys.argv[4].replace('_', ' '))
    self.driver.find_element(By.ID, "id_numerocni").click()
    self.driver.find_element(By.ID, "id_numerocni").send_keys(sys.argv[5].replace('_', ' '))
    self.driver.find_element(By.ID, "id_sexe").click()
    dropdown = self.driver.find_element(By.ID, "id_sexe")

    path1 = "//option[. = '" + sys.argv[7].replace('_', ' ').upper() + "']"
    dropdown.find_element(By.XPATH, path1).click()
    self.driver.find_element(By.ID, "id_adresse").click()
    self.driver.find_element(By.ID, "id_adresse").send_keys(sys.argv[8].replace('_', ' '))
    self.driver.find_element(By.ID, "id_telephone").click()
    self.driver.find_element(By.ID, "id_telephone").send_keys(sys.argv[9].replace('_', ' '))
    self.driver.find_element(By.ID, "id_email").click()
    self.driver.find_element(By.ID, "id_email").send_keys(sys.argv[10].replace('_', ' '))
    
    self.driver.find_element(By.ID, "id_statutmarital").click()
    # dropdown = self.driver.find_element(By.ID, "id_statutmarital")
    # path7 = "//option[. = '" + sys.argv[11].upper() + "']"
    # dropdown.find_element(By.XPATH, path7).click()
    select_5 = Select(self.driver.find_element(By.ID, 'id_statutmarital'))
    select_5.select_by_value(sys.argv[11].replace('_', ' ').upper())

    self.driver.find_element(By.ID, "id_premierelangue").click()
    dropdown = self.driver.find_element(By.ID, "id_premierelangue")
    path8 = "//option[. = '" + sys.argv[12].replace('_', ' ').upper() + "']"
    dropdown.find_element(By.XPATH, path8).click()

    self.driver.find_element(By.ID, "id_statutprofessionnel").click()
    self.driver.find_element(By.CSS_SELECTOR, 'input[value="Suivant"]').click()
    # print("qetqpa 1")
    self.driver.implicitly_wait(30)

    # self.driver.find_element(By.ID, "id_paiement").click()
    # dropdown = self.driver.find_element(By.ID, "id_paiement")
    # path9 = "//option[. = '" + sys.argv[14].upper() + "']"
    # dropdown.find_element(By.XPATH, path9).click()

    # select_4 = Select(self.driver.find_element(By.ID, 'id_paiement'))
    # select_4.select_by_value(sys.argv[14].upper())

    self.driver.find_element(By.CSS_SELECTOR, 'input[name="numerotransaction"]').click()
    self.driver.find_element(By.CSS_SELECTOR, 'input[name="numerotransaction"]').send_keys(sys.argv[15].replace('_', ' '))
    # print("qetqpa 2")
    self.driver.find_element(By.NAME, "bouton_autre").click()
    self.driver.find_element(By.ID, "id_nationalite").click()

    
    self.driver.implicitly_wait(30)
    # print("qetqpa 3")
    # dropdown = self.driver.find_element(By.ID, "id_nationalite")
    # path2 = "//option[. = '" + sys.argv[16] + "']"
    # dropdown.find_element(By.XPATH, path2).click()
    select_5 = Select(self.driver.find_element(By.ID, 'id_nationalite'))
    select_5.select_by_value(sys.argv[16].replace('_', ' '))

    self.driver.implicitly_wait(60)
    select_6 = Select(self.driver.find_element(By.ID, 'id_regionorigine'))
    select_6.select_by_value(sys.argv[17].replace('_', ' '))


    # self.driver.find_element(By.ID, "id_regionorigine").click()
    # dropdown = self.driver.find_element(By.ID, "id_regionorigine")
    # path10 = "//option[. = '" + sys.argv[17].upper() + "']"
    # dropdown.find_element(By.XPATH, path10).click()
    
    self.driver.implicitly_wait(60)
    self.driver.find_element(By.ID, "id_departementorigine").click()
    dropdown = self.driver.find_element(By.ID, "id_departementorigine")
    path3 = "//option[. = '" + sys.argv[18].replace('_', ' ') + "']"
    dropdown.find_element(By.XPATH, path3).click()

    self.driver.find_element(By.ID, "id_departementorigine").click()
    dropdown = self.driver.find_element(By.ID, "id_departementorigine")
    path4 = "//option[. = '" + sys.argv[18].replace('_', ' ') + "']"
    dropdown.find_element(By.XPATH, path4).click()

    self.driver.find_element(By.ID, "id_nompere").click()
    self.driver.find_element(By.ID, "id_nompere").send_keys(sys.argv[19].replace('_', ' '))
    self.driver.find_element(By.ID, "id_professionpere").click()
    self.driver.find_element(By.ID, "id_professionpere").send_keys(sys.argv[20].replace('_', ' '))
    self.driver.find_element(By.ID, "id_nommere").click()
    self.driver.find_element(By.ID, "id_nommere").send_keys(sys.argv[21].replace('_', ' '))
    self.driver.find_element(By.ID, "id_professionmere").click()
    self.driver.find_element(By.ID, "id_professionmere").send_keys(sys.argv[22].replace('_', ' '))
    self.driver.find_element(By.ID, "id_nomurgence").click()
    self.driver.find_element(By.ID, "id_nomurgence").send_keys(sys.argv[23].replace('_', ' '))
    self.driver.find_element(By.ID, "id_telurgence").send_keys(sys.argv[24].replace('_', ' '))
    self.driver.find_element(By.ID, "id_villeurgence").send_keys(sys.argv[25].replace('_', ' '))
    self.driver.find_element(By.NAME, "bouton_filiation").click()

    
    self.driver.implicitly_wait(60)
    

    self.driver.find_element(By.ID, "id_niveau").click()
    dropdown = self.driver.find_element(By.ID, "id_niveau")
    path5 = "//option[. = '" + sys.argv[27].replace('_', ' ').upper() + "']"
    dropdown.find_element(By.XPATH, path5).click()
    
    
    # self.driver.find_element(By.ID, "id_premierchoix").click()
    # dropdown = self.driver.find_element(By.ID, "id_premierchoix")
    # dropdown.find_element(By.XPATH, "//option[. = 'ICT for DEVELOPMENT']").click()

    select_1 = Select(self.driver.find_element(By.ID, 'id_premierchoix'))
    select_1.select_by_value(sys.argv[28].replace('_', ' '))
    
    
    select_2 = Select(self.driver.find_element(By.ID, 'id_secondchoix'))
    select_2.select_by_value(sys.argv[29].replace('_', ' '))
    
    select_3 = Select(self.driver.find_element(By.ID, 'id_troisiemechoix'))
    select_3.select_by_value(sys.argv[30].replace('_', ' '))
    
    # self.driver.find_element(By.ID, "id_secondchoix").click()
    # dropdown = self.driver.find_element(By.ID, "id_secondchoix")
    # dropdown.find_element(By.XPATH, "//option[. = 'INFORMATIQUE']").click()
    
    
    # self.driver.find_element(By.ID, "id_troisiemechoix").click()
    # dropdown = self.driver.find_element(By.ID, "id_troisiemechoix")
    # dropdown.find_element(By.XPATH, "//option[. = 'CHIMIE']").click()
    # //*[@id="actions"]/a[3]
    
    
    self.driver.find_element(By.ID, "id_statutdesire").click()
    dropdown = self.driver.find_element(By.ID, "id_statutdesire")
    path11 = "//option[. = '" + sys.argv[31].replace('_', ' ') + "']"
    dropdown.find_element(By.XPATH, path11).click()

    self.driver.find_element(By.NAME, "bouton_faculte").click()
    
    self.driver.find_element(By.ID, "id_diplome").click()
    dropdown = self.driver.find_element(By.ID, "id_diplome")
    path12 = "//option[. = '" + sys.argv[32].replace('_', ' ').upper() + "']"
    dropdown.find_element(By.XPATH, path12).click()

    self.driver.find_element(By.ID, "id_serie").click()
    dropdown = self.driver.find_element(By.ID, "id_serie")
    path6 = "//option[. = '" + sys.argv[33].replace('_', ' ').upper() + "']"
    dropdown.find_element(By.XPATH, path6).click()

    self.driver.find_element(By.ID, "id_anneeobtention").click()
    self.driver.find_element(By.ID, "id_anneeobtention").send_keys(sys.argv[34].replace('_', ' '))
    self.driver.find_element(By.ID, "id_moyenne").click()
    self.driver.find_element(By.ID, "id_moyenne").send_keys(sys.argv[35].replace('_', ' '))

    self.driver.find_element(By.ID, "id_emetteur").click()

    self.driver.find_element(By.ID, "id_detailjury").click()
    dropdown = self.driver.find_element(By.ID, "id_detailjury")
    path13 = "//option[. = '" + sys.argv[36].replace('_', ' ').upper() + "']"
    dropdown.find_element(By.XPATH, path13).click()
    
    self.driver.find_element(By.ID, "id_emetteur").click()
    self.driver.find_element(By.ID, "id_emetteur").send_keys(sys.argv[37].replace('_', ' '))
    self.driver.find_element(By.ID, "id_date_emission").click()
    self.driver.find_element(By.ID, "id_date_emission").send_keys(sys.argv[38].replace('_', ' '))
    self.driver.find_element(By.NAME, "bouton_diplome").click()
    self.driver.find_element(By.ID, "id_sport_1").click()
    self.driver.find_element(By.ID, "id_art_11").click()
    self.driver.find_element(By.ID, "id_handicap_2").click()
    self.driver.find_element(By.NAME, "bouton_sport").click()
    self.vars["window_handles"] = self.driver.window_handles
    
    link = self.driver.find_element(By.LINK_TEXT, "Telecharger sa fiche").get_attribute('href')
    print(f"{link}")
    self.driver.find_element(By.LINK_TEXT, "Telecharger sa fiche").click()
    self.vars["win5287"] = self.wait_for_window(2000)
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win5287"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])


# scraper = TestFinish()

# try:
#   scraper.setup_method()
# except:
#   print("Une erreur est survenue")

# # scraper.wait_for_window()
# scraper.test_finish()
# scraper.teardown_method()
# path1 = "//option[. = '" + sys.argv[6].upper() + "']"

def execute () : 
  scraper = TestFinish()
  scraper = TestFinish()
  scraper.setup_method()

  # scraper.wait_for_window()
  scraper.test_finish()
  scraper.teardown_method()  

env = os.environ.copy()
env['PYTHONPATH'] = 'c:\Users\admin\AppData\Local\Microsoft\WindowsApps\python'

p = Popen([sys.executable, '-c', 'execute()'], env=env)

print('test')
# print(sys.argv[18] .replace('_', ' '))